### PR TITLE
updated suggestions.md - added few suggestions as mentioned in issue #6

### PR DESCRIPTION
**Pull request by NirmalSilwal**
I have added competition winning project link and dataset provided by Facebook for the challenge in suggestion section.

Below is the snapshot of my proposed ideas.

Nirmal suggestion 1
mpetition dataset released by Facebook.

Do let me know about this first suggestion.

Thanks

### CODE REVIEW

**Review by piyushchandra357 — COMMENTED** [review]
Hi @NirmalSilwal , I have reviewed your commits. 
add your name in the section where you have added your suggestions.

**Comment by piyushchandra357** [comment]
Your suggestions are very Interesting. We'll look into them for sure.

**Comment by NirmalSilwal** [comment]
okay I will add my name. Also I will be doing more research on this project and looking to contribute more.

**Comment by piyushchandra357** [comment]
Sure! I'm looking forward to your contribution.

**Pull request merged**
