### PR TITLE
Add dataset for deepfake

### PR DESCRIPTION
**Pull request by gaurang7goel**
Added images in dataset.
- Some files were not visible so cannot be sure of duplicity.

### CODE REVIEW

**Comment by piyushchandra357** [comment]
@gaurang7goel provide description while opening a PR. Also, kindly check the existing data set images. Try to not make PRs for duplicate images.

**Review by piyushchandra357 — CHANGES_REQUESTED** [review]
dataset is duplicate

**Comment by gaurang7goel** [comment]
so sorry , wont repeat it.

**Comment by gaurang7goel** [comment]
Actually it is my first time to open source

**Comment by piyushchandra357** [comment]
no worries. please make the requested changes.

**Comment by gaurang7goel** [comment]
Done, pls check ones.

**Review by piyushchandra357 — CHANGES_REQUESTED** [review]
delete the file deep fake- 25.png. that already exists

**Comment by gaurang7goel** [comment]
ok

**Comment by gaurang7goel** [comment]
Sorry sir i was unable to find deepfake-25 rest tthe duplicate one i  already deleted

**Comment by gaurang7goel** [comment]
Founded and deleted.

**Pull request merged**
